# fly.toml app configuration file generated for singularity on 2023-11-18T10:12:17+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "singularity"
primary_region = "cdg"

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[mounts]
source = "litefs"
destination = "/var/lib/litefs"
